name: lti_workspace
publish_to: none
environment:
  sdk: ^3.13.0
workspace:
  - packages/lti
  - packages/lti_shelf
dev_dependencies:
  lints: ^6.1.0
  melos: ^8.9.0
  pub_semver: ^2.2.1
  test: ^1.31.1
  yaml: ^3.1.4
melos:
  repository: https://github.com/fischerscode/lti.dart
  sdkPath: .fvm/flutter_sdk
  command:
    version:
      branch: main
      message: 'chore(release): publish packages'
      releaseUrl: true
      changelogFormat:
        includeDate: true
        groupByType: true
      hooks:
        preCommit: |
          dart pub get --offline
          git add pubspec.lock
  scripts:
    test:release:
      run: dart test test/release_test.dart
    analyze:
      run: dart analyze --fatal-infos
    format:
      run: dart format .
    format:check:
      run: dart format --output=none --set-exit-if-changed .
    docs:
      run: >-
        dart doc --validate-links --output build/api/lti packages/lti &&
        dart doc --validate-links --output build/api/lti_shelf packages/lti_shelf
    test:
      exec:
        command: dart test
        concurrency: 1
        failFast: true
      packageFilters:
        dirExists: test
